### ISSUE TITLE
New feature request

### ISSUE THREAD

**Issue by phuongph** [uc-cdis/indexd#72] opened 2018-01-20 19:08 UTC
I think it will be very nice if `indexd` supports bulk input. Most of the regular use cases are good, each insertion takes roughly 25 milliseconds. I think if we insert 1000 entries at a time, it will take much less than `25ms x 1000 = 25s`.

Two use cases will benefit significantly:

1. `backup-indexd-populator` takes 24-26 hours now to populate 1.8-1.9 million entries. It will take significant less  time(hopefully 30-60 minutes)

2. `signpost-2-indexd` migration takes about 60-70 hours (depending on environment) to migrate about 3.5 million entries. It will take much less time (probably  60-90 minutes)

**Comment by zflamig** [comment] 2018-02-27 17:26
Duplicate of #58

**Closed by zflamig** 2018-02-27 17:26 UTC
